# Generated by Django 4.2.5 on 2023-09-09 13:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='current_utc_time',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='info',
            name='day_of_week',
            field=models.CharField(default='Monday', max_length=20),
        ),
    ]
