# Generated by Django 4.2.5 on 2023-09-09 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_info_current_utc_time_alter_info_day_of_week'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Info',
        ),
    ]
